### ISSUE TITLE
fsm_splice_comp.csv

### ISSUE THREAD

**Issue by haowBio** [LuyiTian/FLTseq_data#1]
Hi ,
I am trying to utilize the tr_classify analysis script, and I am just wondering how the fsm_splice_comp.csv create (I have runed FLAMES pipeline,however no this file in the output)?

(Line 43)

fsm_splice_comp <- read.csv(file.path(data_dir,"fsm_splice_comp.csv"), header=FALSE, stringsAsFactors=FALSE)
Thank you

**Comment by LuyiTian** [comment]
they are in the FLTSA_output subfolder in the zip folder. the FLAMES pipeline has a old name called FLTSA.

**Comment by haowBio** [comment]
> they are in the FLTSA_output subfolder in the zip folder. the FLAMES pipeline has a old name called FLTSA.

Thank you for you replay,
 However in the current version of FLAMES pipeline，`fsm_splice_comp.csv`not included in the output right? Because I have finished the pipeline, but did not find the file.

**Comment by LuyiTian** [comment]
it is not a part of the FLAMES pipeline. it is the output file from SQANTI2/SQANTI3 pipeline.
